### ISSUE TITLE
Name can include numbers/invalid chars, Year Level Option not varies per degree program, Inability to Sign Out

### ISSUE THREAD

**Issue by cyboryan** [ssarljames/cs3-portal#2]
## Students ##
- **Name can include numbers or invalid characters.** Since PHP is used for backend, I hope this code I'll quote below may help. I've been using this on some of my projects lately.

The first part of if statement `!(str_replace ... == 0)` checks the field for integers. The second part `!(strlen($firstName) ... $lastName))` checks for invalid characters. It current only bypasses enye, as of now. If there are any additions or changes to make, let me know your thoughts and I may ship those ideas to the project I'm working atm.

`
        if(
            !(
                str_replace(['+', '-'], '', filter_var($firstName, FILTER_SANITIZE_NUMBER_INT)) == 0 &&
                str_replace(['+', '-'], '', filter_var($middleName, FILTER_SANITIZE_NUMBER_INT)) == 0 &&
                str_replace(['+', '-'], '', filter_var($lastName, FILTER_SANITIZE_NUMBER_INT)) == 0
            ) 
                ||
            !(
                strlen($firstName) == strlen(preg_replace('/[^A-Za-zÑñ\s.]/', '', $firstName)) &&
                strlen($middleName) == strlen(preg_replace('/[^A-Za-zÑñ\s.]/', '', $middleName)) &&
                strlen($lastName) == strlen(preg_replace('/[^A-Za-zÑñ\s]/', '', $lastName))
            )
        )
`

![image](https://user-images.githubusercontent.com/32955000/82974145-db25e680-a00b-11ea-9548-425e460c496d.png)

- ** Year Level Option may vary from degree program. ** Currently, all degrees may have an option up to 6th year. Though, this is just a minor issue.

## Others ##
- ** Missing Sign Out Button ** (I can't log out though ^^)

**Comment by ssarljames** [comment]
Thank you for raising this issue.

By the way please file a separate issue on each bug/feature suggestion to help organizing things.

**Comment by cyboryan** [comment]
Okay. Will do it next time. Thanks for the quick response!

**Comment by cyboryan** [comment]
Removed the rest unfixed on new latest commit and will be reissued separately for organization.

**Comment by cyboryan** [comment]
I'll try crafting the solution for the Strict VSU ID Format Issue. :))
